display{number,resolution}: Compatibility: Require Python 3.0
With Python 2.6, displayresolution --primary will print "(1280, ' ', 768)" instead of "1280 768" (which leads to bad parsing in clients), and displaynumber fails with:
> displaynumber:4: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gdk
> Traceback (most recent call last):
>   File "/home/inkarkat/bin/ingo/shell-system/bin/displaynumber", line 6, in <module>
>     print(Gdk.Display.get_default().get_n_monitors())
> AttributeError: 'NoneType' object has no attribute 'get_n_monitors'